# Data filtering rules applied before train/val/test split.
#
# Goal: keep the feature store intact (features_*.parquet) but generate
# train/val/test splits that exclude out-of-scope lines.

# Exclude by `road_type` from `data/processed/transport_meta.parquet`.
# Observed values in this repo: OTOYOL, RAYLI, DENİZ
exclude_road_types: []

# Exclude by exact `line_name` match.
exclude_line_names:
  - "130"
  - "131"
  - "131B"
  - "131S"
  - "133"
  - "13A"
  - "16K"
  - "16Y"
  - "18S"
  - "19B"
  - "21B"
  - "22M"
  - "252"
  - "31K"
  - "35A"
  - "36T"
  - "37"
  - "38M"
  - "39"
  - "39M"
  - "42M"
  - "47"
  - "49"
  - "50"
  - "55B"
  - "69A"
  - "76E"
  - "76T"
  - "80"
  - "81"
  - "82S"
  - "83O"
  - "92A"
  - "93C"
  - "94"
  - "94Y"
  - "97B"
  - "97H"
  - "98K"
  - "99"
  - "ADA_TAKSI"
  - "D1"
  - "D2"
  - "E-9"
  - "HT2"
  - "LF"
  - "MK1"
  - "MK2"
  - "MK3"
  - "MK4"
  - "MR2"
  - "R2"
  - "R3"
  - "R4"
  - "11BD"
  - "11CT"
  - "11N"
  - "11SM"
  - "11V"
  - "121CS"
  - "130M"
  - "131A"
  - "131C"
  - "131H"
  - "131TD"
  - "131Ü"
  - "131YD"
  - "132V"
  - "139U"
  - "13TA"
  - "146BA"
  - "146K"
  - "152K"
  - "16KH"
  - "16N"
  - "19FK"
  - "19H"
  - "19SB"
  - "19Z"
  - "21C"
  - "21K"
  - "21U"
  - "300S"
  - "303C"
  - "336MC"
  - "336T"
  - "34T"
  - "34U"
  - "36CE"
  - "36EM"
  - "37A"
  - "37E"
  - "37M"
  - "37T"
  - "37Y"
  - "38G"
  - "38KT"
  - "38T"
  - "399B"
  - "399C"
  - "39A"
  - "39B"
  - "39Ç"
  - "39D"
  - "39K"
  - "39O"
  - "39Y"
  - "41Y"
  - "429"
  - "44B"
  - "46E"
  - "47A"
  - "47Ç"
  - "47E"
  - "47F"
  - "47K"
  - "47L"
  - "47N"
  - "48A"
  - "48E"
  - "48F"
  - "48R"
  - "48Y"
  - "49A"
  - "49B"
  - "49G"
  - "49GB"
  - "49K"
  - "49M"
  - "49T"
  - "49Y"
  - "49Z"
  - "50AB"
  - "50AC"
  - "522B"
  - "522N"
  - "54B"
  - "54Y"
  - "55V"
  - "59S"
  - "75O"
  - "76BT"
  - "76L"
  - "76SM"
  - "76Y"
  - "78FB"
  - "78M"
  - "85T"
  - "9"
  - "94A"
  - "99Y"
  - "ARN1"
  - "ARN11"
  - "ARN2"
  - "ARN4"
  - "ARN6"
  - "ARN9"
  - "BA-3"
  - "E-11"
  - "EC1"
  - "GZ2"
  - "H-10"
  - "H-11"
  - "H-4"
  - "H-9"
  - "H.K.S"
  - "HS1"
  - "HT14"
  - "KM20"
  - "KM22"
  - "KM40"
  - "MK17"
  - "MK21"
  - "MK32"
  - "MK36"
  - "MK41"
  - "MK51"
  - "MK52"
  - "MK92"
  - "MR10"
  - "MR41"
  - "TURİSTİK HAT"
  - "UM12"
  - "UM22"
  - "UM30"
  - "TUNEL"
  - "NOSTRAM"
  - "TCDD-HB"
  - "TCDD-SK"
  - "TCDD-GH"
  - "İDO-İST2"
  - "USKUDAR-EMN"
  - "BOSTANCI-KRK"
  - "KARAKOY-USK"
  - "ASIYAN-AND"
  - "USKUDAR-KDK"
  - "ADALAR-BST"
  - "E.KADIKOY-BSK"
  - "EMINONU-KDK"
  - "ÇENGELKÖY-KBT"
  - "AVC-KDK-AVC"
  - "BSN-KBT"
  - "BEYKOZ-SAR"
  - "İDO-KRFZ"
  - "ORTAKOY-USK"
  - "DT-İST"
  - "PT-ADA"
  - "EMINONU-USK"
  - "BOSTANCI-ADA"
  - "KABATAS-Y.KDK"
  - "USKUDAR-BSK"
  - "USKUDAR-KBT"
  - "Y.KADIKOY-EMN"
  - "BOGAZ"
  - "MT-ADA"
  - "E.KADIKOY-ADA"
  - "USKUDAR-ORT"
  - "ASIYAN-USK"
  - "Y.KADIKOY-KRK"
  - "BST-KBT-BST"
  - "KABATAS-USK"
  - "MALTEPE-ADA"
  - "Y.KADIKOY-KBT"
  - "BEYKOZ-YKY"
  - "KADIKOY-ORT"
  - "USKUDAR-KRK"
  - "ETKİNLİK"
  - "BSN-BKR"
  - "ADALAR-KBT"
  - "KADIKOY-EMN"
  - "CUBUKLU-IST"
  - "KABATAS-ADA"
  - "KARAKOY-KDK"
  - "ORTAKOY-KDK"
  - "İDO-İST"
  - "USKUDAR-BGZ"
  - "USKUDAR-ASY"
  - "ANADOLU-ASY"
  - "SARIYER-BEY"
  - "KARAKOY-Y.KDK"
  - "YENIKOY-BKZ"
  - "ISTINYE-CBK"
  - "HALIC"
  - "BESIKTAS-USK"
  - "İDO-ADA2"
  - "BARBAROS-E.KDK"
  - "E.KADIKOY-BGZ"
  - "KARAKOY-BST"
  - "BESIKTAS-ADA"
  - "YNK-ADA"
  - "BOSTANCI-AVC"
  - "AVCILAR - BST"
